<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4b7e2ae0-45ff-441f-9de8-9ceacd38aff2</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parrot.Application\Parrot.Application.csproj" />
    <ProjectReference Include="..\Parrot.Grpc.Contracts\Parrot.Grpc.Contracts.csproj" />
    <ProjectReference Include="..\Parrot.Infrastructure\Parrot.Infrastructure.csproj" />
  </ItemGroup>

</Project>
