<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WhatsAppMessageIngestor-a3761470-829f-45fb-8c3a-9fb07667b788</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parrot.Application\Parrot.Application.csproj" />
    <ProjectReference Include="..\Parrot.Infrastructure\Parrot.Infrastructure.csproj" />
  </ItemGroup>

</Project>
